### ISSUE TITLE
Any sample of EC-KCDSA

### ISSUE THREAD

**Issue by kamakuba** [johndoe31415/joeecc#6]
Hello!
Can provide any working samples of ec-kcdsa using joeecc
eckcdsa_sign
eckcdsa_sign_hash
eckcdsa_verify
eckcdsa_verify_hash

**Comment by johndoe31415** [comment]
Hi, I'm not sure I understand correctly. Do you have working samples which you would like to merge upstream? If so, please do create a PR and I'd be happy to review it. Thank you!

**Comment by kamakuba** [comment]
no no, i'm asking about your experience in this field (ec-kcdsa)...
May be you have some working samples... ?

**Comment by johndoe31415** [comment]
Hey, sorry I do not, I've never worked with EC-KCDSA before.

**Comment by zugzwang** [comment]
Have a look at e.g. libecc, botan. Also there are some specs with test vectors.
